<<<<<<< HEAD
# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Markdown specs
=======
# Site settings

title: Strata # Title of your site
email: himanshumisra1990@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hmisra.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     himanshumisra  # Replace this with your Twitter username
github_username:      hmisra  # Replace this with your GitHub username
linkedin_username:    example  # Replace this with your LinkedIn username
google_plus_username: example  # Replace this with your Google+ username
facebook_username:    example  # Replace this with your Facebook username
dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
>>>>>>> origin/master
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               Ed.
tagline:             'A Jekyll theme for minimal editions'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 https://github.com/elotroalex/ed
baseurl:             '/ed'

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Custom vars
version:             0.0.3

# Gems
gems: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/ed/bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

